const time = 10; 
const quizData = [
  {
    "question": "What is the name of the algorithm used by GPT-4?",
    "inputType": "checkbox", 
    "options": [
      { "text": "Generative Adversarial Network" },
      { "text": "Artificial Neural Network" },
      { "text": "Transformer Architecture" },
      { "text": "Q-learning" }
    ],
    "correct": 2
  },
  {
    "question": "What common issue in AI-generated images involves incorrect positioning of body parts, especially noted with fingers?",
    "inputType": "radio",
    "options": [
      { "text": "Mode collapse" },
      { "text": "Artifact" },
      { "text": "Overfit" },
      { "text": "Latent space" }
    ],
    "correct": 1
  },
  {
    "question": "What is the name of the company that aims to enhance tunneling speed enough such that establishing a tunnel network is financially feasible, which is owned by Elon Musk?",
    "inputType": "radio",
    "options": [
      { "text": "Neuralink" },
      { "text": "SpaceX" },
      { "text": "Boring Company" },
      { "text": "OpenAI" }
    ],
    "correct": 2
  },
  {
    "question": "What is the implantable brain computer capable of translating thoughts into actions?",
    "inputType": "radio",
    "options": [
      { "text": "Synchron" },
      { "text": "Emotiv" },
      { "text": "BrainCo" },
      { "text": "Neuralink" }
    ],
    "correct": 3
  },
  {
    "question": "What is the term for the technique used to improve images generated by upscaling in NVIDIA's DLSS technology?",
    "inputType": "radio",
    "options": [
      { "text": "Raytracing" },
      { "text": "FSR" },
      { "text": "sharpening" },
      { "text": "FPS Boost" }
    ],
    "correct": 0
  },
  {
    "question": "Name a common test used to determine if a machine can exhibit human-like intelligence.",
    "inputType": "radio",
    "options": [
      { "text": "AI benchmarking" },
      { "text": "Turing test" },
      { "text": "Adversarial test" },
      { "text": "CAPTCHA" }
    ],
    "correct": 1
  },
  {
    "question": "Name the thing which revolutionized the ability of computers by enhancing their capabilities and become popular due to the rise of AI, what is that?",
    "inputType": "radio",
    "options": [
      { "text": "RAM" },
      { "text": "GPU" },
      { "text": "TPU" },
      { "text": "CPU" }
    ],
    "correct": 1
  },
  {
    "question": "The latest tech innovation that speeds up development by using AI which developed by a company called Cognition?",
    "inputType": "radio",
    "options": [
      { "text": "Gemini-AI" },
      { "text": "Copilot" },
      { "text": "GPT-4" },
      { "text": "Devin-AI" }
    ],
    "correct": 1
  },
  {
    "question": "What is the name of the first “computer virus” which targeted APARNET, the precursor to the internet?",
    "inputType": "radio",
    "options": [
      { "text": "Creeper" },
      { "text": "Lovebug" },
      { "text": "Stuxnet" },
      { "text": "Saaser" }
    ],
    "correct": 0
  },
  {
    "question": "Until Alan Emtage, a native of Barbados, created the world's first search engine, What is the name of the world’s first search engine?",
    "inputType": "radio",
    "options": [
      { "text": "Google" },
      { "text": "Archie" },
      { "text": "Bing" },
      { "text": "Yahoo" }
    ],
    "correct": 1
  },
  {
    "question": "What technology used behind the creation of Satoshi Nakamoto?",
    "inputType": "radio",
    "options": [
      { "text": "Deep learning" },
      { "text": "IOT" },
      { "text": "Block chain" },
      { "text": "Virtual reality" }
    ],
    "correct": 2
  },
  {
    "question": "This device, introduced by a Cupertino-based tech giant, marks their entry into a new product category that blends realities. What is the name of this product?",
    "inputType": "radio",
    "options": [
      { "text": "Meta quest" },
      { "text": "Vision pro" },
      { "text": "Holo lens" },
      { "text": "Playstation VR" }
    ],
    "correct": 1
  },
  {
    "question": "Python, known for its multi-purpose and dead slow execution, but this parallel computing model enhanced its speed, what is it?",
    "inputType": "checkbox",
    "options": [
      { "text": "CUDA" },
      { "text": "Tensor" },
      { "text": "Registers" },
      { "text": "Threads" }
    ],
    "correct": 0
  },
  {
    "question": "What is the name of the standard communication protocol that is crucial for enabling low-power IoT devices to connect to the internet directly via widely used mobile networks?",
    "inputType": "radio",
    "options": [
      { "text": "MQTT" },
      { "text": "SMTP" },
      { "text": "POP3" },
      { "text": "API" }
    ],
    "correct": 0
  },
  {
    "question": "Nokia 6131 first used this technology which enables two devices, such as smartphones and payment terminals, to communicate when they are brought within a few centimeters of each other, name that technology",
    "inputType": "radio",
    "options": [
      { "text": "Wifi" },
      { "text": "Zigbee" },
      { "text": "UPI" },
      { "text": "NFC" }
    ],
    "correct": 3
  },
  {
    "question": "Emoji widely used in text-based conversation to reflect one’s reaction, name the person who designed the concept of emoji",
    "inputType": "radio",
    "options": [
      { "text": "Charles Babbage" },
      { "text": "Shigeta Kurita" },
      { "text": "John Macarthy" },
      { "text": "Fu Jeing" }
    ],
    "correct": 1
  },
  {
    "question": "What North Carolina-based game company created the 2018 game “Fortnite?”",
    "inputType": "radio",
    "options": [
      { "text": "Activision" },
      { "text": "Unity" },
      { "text": "Epic" },
      { "text": "Sony" }
    ],
    "correct": 2
  },
  {
    "question": "What is the official name for the “prove you’re not a robot” tests that websites sometimes require?",
    "inputType": "radio",
    "options": [
      { "text": "CAPTCHA" },
      { "text": "ReCAPTCHA" },
      { "text": "Authentication Test" },
      { "text": "Verify-Pass" }
    ],
    "correct": 0
  },
  {
    "question": "Which University offered the first-ever academic program in Computer Science?",
    "inputType": "checkbox",
    "options": [
      { "text": "MIT" },
      { "text": "Prude university" },
      { "text": "Harvard" },
      { "text": "Stanford" }
    ],
    "correct": 0
  },
  {
    "question": "Sonos .Inc, an American-based company, what is it famous for?",
    "inputType": "radio",
    "options": [
      { "text": "Speakers" },
      { "text": "Camera" },
      { "text": "Keyboard" },
      { "text": "Display" }
    ],
    "correct": 0
  }
]
const questionsPerPage = 5;
let currentPage = 0;
let selectedAnswers = Array(quizData.length).fill(null);
let intervalId;

function initializeTimer() {
  const endTime = localStorage.getItem('endTime');
  if (!endTime) {
    const newEndTime = Date.now() + time * 60 * 1000;
    localStorage.setItem('endTime', newEndTime);
  }
}

function updateTimer() {
  const endTime = localStorage.getItem('endTime');
  if (endTime) {
    const currentTime = Date.now();
    const remainingTime = endTime - currentTime;
    
    if (remainingTime >= 0) {
      const minutes = Math.floor((remainingTime / 1000) / 60);
      let seconds = Math.floor((remainingTime / 1000) % 60);
      seconds = seconds < 10 ? '0' + seconds : seconds;
      document.getElementById('cd').innerHTML = `${minutes}:${seconds}`;
    } else {
      clearInterval(intervalId);
      document.getElementById('cd').innerHTML = '0:00';
      alert('Time is up! Your quiz has ended.');
      validateAllAnswers();
    }
  }
}

function renderPage(page) {
  const container = document.getElementById('quiz-container');
  const submitBtnContainer = document.getElementById('submitbtn');
  const prevBtn = document.getElementById('prev');
  const nextBtn = document.getElementById('next');

  container.innerHTML = '';
  submitBtnContainer.innerHTML = '';

  const startIndex = page * questionsPerPage;
  const endIndex = Math.min(startIndex + questionsPerPage, quizData.length);

  for (let i = startIndex; i < endIndex; i++) {
    const question = quizData[i];
    const inputType = question.inputType;
    const options = question.options;

    container.innerHTML += `<h2 class="question">${question.question}</h2>`;
    container.innerHTML += `<div class="options">`;

    if (inputType === "radio") {
      options.forEach((option, index) => {
        container.innerHTML += `
          <div>
            <input type="radio" name="option${i}" id="option${i}-${index}" value="${index}" ${selectedAnswers[i] === index ? 'checked' : ''}>
            <label for="option${i}-${index}">${option.text}</label>
          </div>`;
      });
    }  
    else if (inputType === "checkbox") {
      options.forEach((option, index) => {
        container.innerHTML += `
          <div>
            <input type="checkbox" name="option${i}-${index}" id="option${i}-${index}" value="${index}" ${selectedAnswers[i] && selectedAnswers[i].includes(index) ? 'checked' : ''}>
            <label for="option${i}-${index}">${option.text}</label>
          </div>`;
      });
    }
    container.innerHTML += `</div>`;
  }

  prevBtn.style.display = (page === 0) ? 'none' : 'inline-block';

  if (page === Math.ceil(quizData.length / questionsPerPage) - 1) {
    nextBtn.style.display = 'none';
    submitBtnContainer.innerHTML = `<button id="submit" onclick="submitQuiz()">Submit</button>`;
  } 
  else {
    nextBtn.style.display = 'inline-block';
  }
}

function collectAnswers() {
  const container = document.getElementById('quiz-container');
  const inputs = container.querySelectorAll('input[type="radio"]:checked, input[type="checkbox"]:checked, input[type="text"]');
  
  inputs.forEach(input => {
    const questionIndex = parseInt(input.name.replace('option', ''));
    const optionIndex = input.value;
    
    if (input.type === 'checkbox') {
      if (!selectedAnswers[questionIndex]) {
        selectedAnswers[questionIndex] = [];
      }
      selectedAnswers[questionIndex].push(parseInt(optionIndex));
    } 
    else if (input.type === 'text') {
      selectedAnswers[questionIndex] = input.value.trim();
    } 
    else {
      selectedAnswers[questionIndex] = parseInt(optionIndex);
    }
  });
}

function validateAllAnswers() {
  const container = document.getElementById('quiz-container');
  const head = document.getElementById("heading");
  head.innerHTML = 'QUIZ RESULTS';
  container.innerHTML = '';
  let score = 0;

  quizData.forEach((question, index) => {
    const selectedAnswer = selectedAnswers[index];
    if (selectedAnswer !== null && selectedAnswer !== undefined) {
      if (Array.isArray(selectedAnswer)) { 
        const correctOptions = question.correct;
        const isCorrect = correctOptions.every(option => selectedAnswer.includes(option));
        if (isCorrect) {
          container.innerHTML += `<p class="correct">Question ${index + 1}: Correct!</p>`;
          score++;
        } 
        else {
          const correctAnswers = correctOptions.map(opt => question.options[opt].text).join(', ');
          container.innerHTML += `<p class="incorrect">Question ${index + 1}: Incorrect. Correct answer(s): ${correctAnswers}</p>`;
        }
      } 
       else if (typeof selectedAnswer === 'number') { 
        if (selectedAnswer === question.correct) {
          container.innerHTML += `<p class="correct">Question ${index + 1}: Correct!</p>`;
          score++;
        } 
        else {
          container.innerHTML += `<p class="incorrect">Question ${index + 1}: Incorrect. Correct answer: ${question.options[question.correct].text}</p>`;
        }
      } 
      else {
        container.innerHTML += `<p class="not-selected">Question ${index + 1}: No answer selected.</p>`;
      }
    } 
    else {
      container.innerHTML += `<p class="not-selected">Question ${index + 1}: No answer selected.</p>`;
    }
  });

  container.innerHTML += `<p>Your score is ${score} out of ${quizData.length}</p>`;
  clearInterval(intervalId);
  localStorage.removeItem('endTime');

  document.getElementById('prev').style.display = 'none';
  document.getElementById('next').style.display = 'none';
  document.getElementById('submitbtn').style.display = 'none';
}

function submitQuiz() {
  collectAnswers();
  validateAllAnswers();
}

function prevPage() {
  if (currentPage > 0) {
    collectAnswers();
    currentPage--;
    renderPage(currentPage);
  }
}

function nextPage() {
  if (currentPage < Math.ceil(quizData.length / questionsPerPage) - 1) {
    collectAnswers();
    currentPage++;
    renderPage(currentPage);
  }
}

document.addEventListener('DOMContentLoaded', () => {
  initializeTimer();
  intervalId = setInterval(updateTimer, 1000);
  renderPage(currentPage);
});

window.addEventListener('beforeunload', () => {
  collectAnswers();
  clearInterval(intervalId);
});
